version: '3.8'

services:
  app:
    build: .
    ports:
      - "3008:3000"
    volumes:
      - ~/qwerty/file:/file
    command: npm start
    restart: unless-stopped

volumes:
  db_data:
    driver: local